# -*- coding: utf-8 -*-
"""basic_transformer_block.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpsynExhwETWK8SEk3Tir8QsAHA-4SZ1

# Import Libraries
"""

import torch
from torch import nn
import pandas as pd

"""# Basic Transformer Block"""

class BasicTransformerBlock(nn.Module):

    def __init__(self, embed_dim, num_heads, ff_dim):
        super().__init__()

        # Self attention layer
        self.attention = nn.MultiheadAttention(embed_dim, num_heads, batch_first=True)
        self.norm1 = nn.LayerNorm(embed_dim)


        # Feed forward layers
        self.feed_forward = nn.Sequential(
            nn.Linear(embed_dim, ff_dim),  # expand
            nn.ReLU(),                      # activation
            nn.Linear(ff_dim, embed_dim),  # compress back

        )

        self.norm2 = nn.LayerNorm(embed_dim)


    def forward(self, x):

        attention_out, _ = self.attention(x, x, x) # apply self attention
        x = x + attention_out # add output to data
        x = self.norm1(x) # normalize & stabelize
        forward_out = self.feed_forward(x) # pass to feed forward net
        x = x + forward_out # add ouput to data
        x = self.norm2(x) # normalize again

        return x

"""Test the block with dummy input"""

block = BasicTransformerBlock(embed_dim=64, num_heads=4, ff_dim=256)
x = torch.rand(2, 10, 64)
output = block(x)

print(f"Input shape:  {x.shape}")
print(f"Output shape: {output.shape}")