# -*- coding: utf-8 -*-
"""fine_tuning_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKpRwpYW3NAR8i3xuWtPflRt3-j5ZzBK

# Import Libraries
"""

import torch
from torch import nn
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer
from torch.optim import AdamW

"""# Read & Clean Data"""

df = pd.read_csv('/content/IT Support Ticket Data.csv', quotechar='"', doublequote=True, engine='python')

def clean_text(text):
    text = str(text)                  # handle NaN values
    text = text.replace('<br>', ' ')  # remove HTML tags
    text = text.replace('<br/>', ' ') # remove HTML tags
    text = ' '.join(text.split())     # remove extra whitespace
    return text

# Apply cleaning
df['Body'] = df['Body'].apply(clean_text)

# Drop empty rows
df = df.dropna(subset=['Body'])

# Take subset
subset = df[df['Department'] == 'Technical Support'].head(60)
texts = subset['Body'].tolist()

# Verify token count is 5000+
total_words = sum(len(t.split()) for t in texts)
estimated_tokens = int(total_words * 1.3) #  1.3 is a well known rule of thumb for english text
print(f"Total tickets: {len(texts)}")
print(f"Total words: {total_words}")
print(f"Estimated tokens: {estimated_tokens}")

if estimated_tokens >= 5000:
    print("Token requirement met, continue")
else:
    print("Need more data")

"""# Save Data"""

import os

os.makedirs('fine_tuning_data', exist_ok=True)

with open("fine_tuning_data/custom_dataset.txt", "w") as f:
    for ticket in texts:
        f.write(ticket + "\n\n")
print("Dataset saved!")

"""# Load Base Model"""

model = AutoModelForCausalLM.from_pretrained("erwanf/gpt2-mini")
model.eval()

"""# Prepare Tokenizer"""

# Load tokenizer

tokenizer = AutoTokenizer.from_pretrained("erwanf/gpt2-mini")
tokenizer.pad_token = tokenizer.eos_token

encodings = tokenizer(
    texts,
    truncation=True,        # cut off if text is too long
    max_length=128,         # max tokens per ticket
    padding=True,           # pad short tickets
    return_tensors="pt"
)

print(f"Input IDs shape: {encodings['input_ids'].shape}")

"""# Generte 5 Base Outputs"""

model.eval()

prompt = "The user is experiencing a technical issue with"

inputs = tokenizer(prompt, return_tensors="pt")

base_outputs = [] # train before fine tuning

for i in range(5):
    output = model.generate(
        inputs['input_ids'],
        max_length=90, # max length of the output
        do_sample=True,  # different output every time
        temperature=0.9 # creativity
    )
    text = tokenizer.decode(output[0], skip_special_tokens=True)
    base_outputs.append(text)
    print(f"Base Output {i+1}:\n{text}\n")

"""# Save the Model"""

model.save_pretrained("base_gpt2_tickets")
tokenizer.save_pretrained("base_gpt2_tickets")
print("Done")

"""# Prepare Data"""

class TicketDataset(Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __len__(self):
        return len(self.encodings['input_ids'])

    def __getitem__(self, idx):
        return {
            'input_ids': self.encodings['input_ids'][idx],
            'attention_mask': self.encodings['attention_mask'][idx],
            'labels': self.encodings['input_ids'][idx]  # labels = input for GPT2
        }

# Create dataset and dataloader
dataset = TicketDataset(encodings)
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

print(f"Dataset size: {len(dataset)} tickets")
print(f"Batches per epoch: {len(dataloader)}")

"""# Set up Training"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

model.config.pad_token_id = tokenizer.pad_token_id

# lr=5e-5 is standard learning rate for fine-tuning LLMs
optimizer = AdamW(model.parameters(), lr=5e-5)

"""# Fine-Tune the Model"""

num_epochs = 5  # minimum required by task

model.train()  # set model to training mode

for epoch in range(num_epochs):
    total_loss = 0

    for batch in dataloader:
        # Move batch to device
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        # Clear gradients from previous batch
        optimizer.zero_grad()

        # Forward pass
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        # Calculate loss and backpropagate
        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(dataloader)
    print(f"Epoch {epoch+1}/{num_epochs} - Loss: {avg_loss:.4f}")

print("Done")

"""# Generate 5 Fine-Tuned Outputs"""

model.eval()

prompt = "The user is experiencing a technical issue with"
inputs = tokenizer(prompt, return_tensors="pt").to(device)

finetuned_outputs = []
for i in range(5):
    output = model.generate(
        inputs['input_ids'],
        max_length=90, # max output length
        do_sample=True, # different output everytime
        temperature=0.9 # creativity
    )
    text = tokenizer.decode(output[0], skip_special_tokens=True)
    finetuned_outputs.append(text)
    print(f"Fine-tuned Output {i+1}:\n{text}\n")

"""# Save the model"""

model.save_pretrained("fine_tuned_gpt2_tickets")
tokenizer.save_pretrained("fine_tuned_gpt2_tickets")
print("Done")

torch.save(model.state_dict(),
           "model_weights.pt")
print("Weights saved!")